version: '3'
services:
  workspace-ex:
    build:
      context: ../docker/workspace-ex
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ./../docker/workspace-ex/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      - "dockerhost_ext:${MACHINE_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2375
    networks:
      - frontend
      - backend
    links:
      - docker-in-docker

  php-fpm-ex:
    build:
      context: ../docker/php-fpm-ex
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ../docker/php-fpm-ex/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2375
      - FAKETIME=${PHP_FPM_FAKETIME}
    networks:
      - backend
    links:
      - docker-in-docker

  nginx-ex:
    build:
      context: ../docker/nginx-ex
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm-ex
    networks:
      - frontend
      - backend

  laravel-horizon-ex:
    build:
      context: ../docker/php-fpm-ex
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ../docker/php-fpm-ex/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ../docker/php-fpm-ex/supervisord.d/:/etc/supervisord.d/
      - ../docker/php-fpm-ex/supervisor.conf:/etc/supervisor.conf
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2375
      - FAKETIME=${PHP_FPM_FAKETIME}
      - START_HORIZON_INSTEAD_OF_FPM=1
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - backend

  localdb:
    image: mariadb:10
    ports:
      - 3306:3306
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  localpostgres:
    image: postgres:10
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql
    networks:
      - backend

  selenoid:
    build:
      context: ../docker/selenoid
    volumes:
      - ../docker/selenoid/:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    command: ["-container-network", "oex_new_backend", "-conf", "/etc/selenoid/browsers.json"]

  selenoid-ui:
    image: aerokube/selenoid-ui
    ports:
      - 8082:8080
    command: "--selenoid-uri 'http://selenoid:4444'"
    networks:
      - frontend
      - backend